spring.application.name=nadok

#Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_ID}
spring.datasource.password=${DB_PW}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
spring.jpa.properties.hibernate.use_sql_comments=true

file.upload-dir=/home/ubuntu/nadok/uploads/profiles/

# Groq API Key
groq.api.key=${GROP_API_KEY}

# Aladin API key
aladin.api.key=${ALADIN_API_KEY}

#Gemini API key
gemini.api.key=${GEMINI_API_KEY}

