# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Aladin API
aladin.api.key=ttbyuny05190417001

# Groq API
groq.api.key=YOUR_GROQ_API_KEY_HERE
